spring.application.name=car-sharing-app

spring.config.import=optional:file:.env[.properties]

spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${MYSQLDB_PASSWORD}
spring.datasource.url=${MYSQLDB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

telegrambots.bot.token=${TELEGRAM_BOT_TOKEN}}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
